name: fwtree
version: 1.1
date: 2018-03-08
description: |
    Computing trees related to some pro-p-groups of finite width

authors:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Tobias Rossmann
      url: mailto:tobias.rossmann@googlemail.com

maintainers:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Tobias Rossmann
      url: mailto:tobias.rossmann@googlemail.com

GAP: ">=4.4"

needed-pkgs:
    - name: "Polycyclic"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "Autpgrp"
      version: ">=1.0"
      url: "https://gap-packages.github.io/autpgrp/"
    - name: "anupq"
      version: ">=1.0"
      url: "https://gap-packages.github.io/anupq/"

suggested-pkgs:
    - name: "XGAP"
      version: ">=1.0"
      url: "https://gap-packages.github.io/xgap"

www: https://gap-packages.github.io/fwtree/
readme: README
packageinfo: https://gap-packages.github.io/fwtree/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/fwtree/releases/download/v1.1/fwtree-1.1.tar.gz

abstract: |
    The <span class="pkgname">fwtree</span> package contains some code related to the computation of trees corresponding to some groups of finite rank, width and obliquity.

status: deposited
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
