name: fwtree
version: 1.0
date: 2009-04-23
description: |
    Computing trees related to some pro-p-groups of finite width

authors:
    - name: Bettina Eick
      url: http://www-public.tu-bs.de:8080/~beick
    - name: Tobias Rossmann
      url: mailto:tobias.rossmann (at) googlemail.com

maintainers:
    - name: Bettina Eick
      url: http://www-public.tu-bs.de:8080/~beick
    - name: Tobias Rossmann
      url: mailto:tobias.rossmann (at) googlemail.com

GAP: ">=4.4"

needed-pkgs:
    - name: "Polycyclic"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "Autpgrp"
      version: ">=1.0"
      url: "http://www.icm.tu-bs.de/~beick/so.html"
    - name: "anupq"
      version: ">=1.0"
      url: "https://gap-packages.github.io/anupq/"

suggested-pkgs:
    - name: "XGAP"
      version: ">=1.0"
      url: "https://gap-packages.github.io/xgap"

www: http://www.maths.nuigalway.ie/~tobias/fwtree/
readme: README
packageinfo: http://www.maths.nuigalway.ie/~tobias/fwtree/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.maths.nuigalway.ie/~tobias/fwtree/fwtree-1.0.tar.gz

abstract: |
    The <span class="pkgname">fwtree</span> package contains some code related to the computation of trees corresponding to some groups of finite rank, width and obliquity.

status: deposited
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
